### ISSUE TITLE
执行器执行任务完成后，调度器无法修改执行结果

### ISSUE THREAD

**Issue by hzhz373241000** [xuanye/DotXxlJob#12]
xxl-job2.3.0版本中，callback api接口的数据格式有变化，所以2边的数据格式不一样，导致无法修改执行结果

xxl-job中
`public HandleCallbackParam(long logId, long logDateTim, int handleCode, String handleMsg) {
        this.logId = logId;
        this.logDateTim = logDateTim;
        this.handleCode = handleCode;
        this.handleMsg = handleMsg;
    }`

DotXxlJob中
`        public HandleCallbackParam(TriggerParam triggerParam, ReturnT result)
        {
            this.LogId = triggerParam.LogId;
            this.LogDateTime = triggerParam.LogDateTime;
            this.ExecuteResult = result;
        }`

**Comment by xuanye** [comment]
xxl-job的问题就是接口一直在变更，包括协议，  已兼容上述问题，谢谢反馈
