### ISSUE TITLE
现在大部分应用都切换https了，咱们执行器注册时填写的地址固定http

### ISSUE THREAD

**Issue by xinghist** [xuanye/DotXxlJob#17]
应该改为读取配置文件判断 http还是https

RegistryValue = $"http://{_options.SpecialBindAddress}:{_options.Port}/"

**Comment by xuanye** [comment]
一般来说，我们内网是不用HTTPS的，如果确实有这个需求，可新增一个SpecialBindUrl，在注册时判断是否存在该配置，优先使用，见本次提交 https://github.com/xuanye/DotXxlJob/commit/e7cd2bcd9fd0859b1c432191c28d84b02b6d83fd
