### ISSUE TITLE
关于iis上部署netcore3.1的不能启动问题

### ISSUE THREAD

**Issue by FatuityCookie** [xuanye/DotXxlJob#18]
同样的配置文件，应用自宿主可以正常注册，并进行任务调度。

但是发布到iis上，不知道为什么不能启动

**Comment by xuanye** [comment]
那你要看错误的日志信息是啥？因为我们不会再IIS下部署。你至少把错误信息贴出来

**Comment by FatuityCookie** [comment]
已经查证是属于iis自动回收
