### ISSUE TITLE
任务取消，未通知到实际执行器，导致真实任务并没有停止

### ISSUE THREAD

**Issue by guochen2** [xuanye/DotXxlJob#23]
现象：如题，当调用停止任务，对CancellationToken进行取消时，实际执行任务里并不知道已经停止了，线程还是会继续执行
期望：将CancellationToken作为参数传入到Executor，实际执行任务里能对CancellationToken进行IsCancellationRequested判断，终止任务。

![image](https://user-images.githubusercontent.com/12321505/148727089-c40720a1-b4df-4705-b012-181f692c4311.png)

**Comment by xuanye** [comment]
遇到了问题，你又有解决方案， 那你应该fork 后pull request 一下 ，: )

**Comment by guochen2** [comment]
> 遇到了问题，你又有解决方案， 那你应该fork 后pull request 一下 ，: )

👍👍👍
