### ISSUE TITLE
不支持https

### ISSUE THREAD

**Issue by myloadcc** [xuanye/DotXxlJob#25]
`        public async Task RegistryAsync(CancellationToken cancellationToken)
        {
            var registryParam = new RegistryParam {
                RegistryGroup = "EXECUTOR",
                RegistryKey = _options.AppName,
                RegistryValue = string.IsNullOrEmpty(_options.SpecialBindUrl)?
                                $"http://{_options.SpecialBindAddress}:{_options.Port}/" : _options.SpecialBindUrl
            };`
这里固定写死了http

**Comment by xuanye** [comment]
#17
