### ISSUE TITLE
地址检测问题

### ISSUE THREAD

**Issue by alanjohn0915** [xuanye/DotXxlJob#28]
我的内网地址  192.122.xxx.xxx
您设置的校验规则
ipABegin = ConvertToNumber("10.0.0.0");
ipAEnd = ConvertToNumber("10.255.255.255");

ipBBegin = ConvertToNumber("172.16.0.0");
ipBEnd = ConvertToNumber("172.31.255.255");

ipCBegin = ConvertToNumber("192.168.0.0");
ipCEnd = ConvertToNumber("192.168.255.255");

_options.SpecialBindAddress = IPUtility.GetLocalIntranetIP().MapToIPv4().ToString();
导致这里抛异常

**Comment by xuanye** [comment]
你这个地址不是内网地址啊，那是你们内网用了外网的IP做了
```
if (string.IsNullOrEmpty(_options.SpecialBindAddress))
            {
                _options.SpecialBindAddress = IPUtility.GetLocalIntranetIP().MapToIPv4().ToString();
            }
```
看代码就可以知道了，你这种情况，配置文件写死一个IP吧
