### ISSUE TITLE
使用自动注册方式报错Connection reset by peer

### ISSUE THREAD

**Issue by wxk0248** [xuanye/DotXxlJob#29]
![微信图片_20220620092838](https://user-images.githubusercontent.com/11935014/174509967-1ff2c816-00c7-40a7-8ca6-1da0c2e520ff.jpg)
你好，我在把一个执行器调整为自动注册以后，每天会不定时抛出来几个Connection reset by peer这样的错误，请教改如何解决

**Comment by xuanye** [comment]
自动注册模式下，会每60秒 向admin 注册一次，表示当前服务正常启用， 你出现的这个错误是超时了，先确保网络稳定。

**Comment by wxk0248** [comment]
好的，我监测下网络稳定性
