### ISSUE TITLE
最新版本xxljob无法上传执行结果

### ISSUE THREAD

**Issue by knowyi** [xuanye/DotXxlJob#31]
hi，你好 我使用最新版本xxljob 2.3.1，使用demo进行测试，执行返回以后xxl管理页面里没有正常执行结果
![image](https://user-images.githubusercontent.com/7392434/183620168-316d9f30-37d1-48cb-a4fa-f04bdfbe9a06.png)
![image](https://user-images.githubusercontent.com/7392434/183620000-f85777ed-3dab-4b3a-8f86-a2a8e5dc7f0c.png)

**Comment by knowyi** [comment]
换成xxljob2.3.0 demo 依然没有执行结果，请问xxljob需要使用什么版本？
![image](https://user-images.githubusercontent.com/7392434/183623395-8c934961-483c-455e-9c21-d7abe60e3c18.png)

**Comment by xuanye** [comment]
在2.2.x做过测试，我晚点看下2.3的问题，xxljob 的api 经常会做些 变更，让人很恼火

**Comment by knowyi** [comment]
> 在2.2.x做过测试，我晚点看下2.3的问题，xxljob 的api 进程会做些 变更，让人很恼火

xxljob github上没看到2.2.x的版本，只找到2.2.0的 但是看你介绍不支持2.2.0，尴尬
https://github.com/xuanye/DotXxlJob/issues/31#issuecomment-1210011194

**Comment by knowyi** [comment]
> 在2.2.x做过测试，我晚点看下2.3的问题，xxljob 的api 进程会做些 变更，让人很恼火

确实是api改了，HandleCallbackParam 加两个字段，ExecuteResult对象没有了，现在执行结果可以正常提交了

![image](https://user-images.githubusercontent.com/7392434/183808900-e8f7265a-aea5-49cd-98d8-1d6e24f90d27.png)

**Comment by knowyi** [comment]
我在做测试的时候有一个问题 阻塞策略设置覆盖之前调度的时候 调用的stop方法会等待前一个task结果，感觉没有覆盖和串行是一个效果
![image](https://user-images.githubusercontent.com/7392434/183875874-ebff3323-080c-45cb-b871-306cd47e11f9.png)

**Comment by xuanye** [comment]
> 我在做测试的时候有一个问题 阻塞策略设置覆盖之前调度的时候 调用的stop方法会等待前一个task结果，感觉没有覆盖和串行是一个效果 ![image](https://user-images.githubusercontent.com/7392434/183875874-ebff3323-080c-45cb-b871-306cd47e11f9.png)

覆盖的前提是那个task 还没开始，是吗？如果任务执行到一半直接取消（如果没有对应的取消逻辑实现）则会产生意想不到的问题

你可以把你的修改 提交一个PR，我会合并到代码中 并发布一个新的版本

**Comment by knowyi** [comment]
> > 我在做测试的时候有一个问题 阻塞策略设置覆盖之前调度的时候 调用的stop方法会等待前一个task结果，感觉没有覆盖和串行是一个效果 ![image](https://user-images.githubusercontent.com/7392434/183875874-ebff3323-080c-45cb-b871-306cd47e11f9.png)
> 
> 覆盖的前提是那个task 还没开始，是吗？如果任务执行到一半直接取消（如果没有对应的取消逻辑实现）则会产生意想不到的问题
> 
> 你可以把你的修改 提交一个PR，我会合并到代码中 并发布一个新的版本

这个问题我没想好怎么改，我不确定 覆盖的前提是task还没有开始执行 还是执行到一半的直接取消 如果说覆盖的前提是需要task还未执行 那这个问题是正确的 不需要修改

**Comment by xuanye** [comment]
>覆盖的前提是task还没有开始执行
我的想法是这个

**Comment by q383186554** [comment]
请问glue模式要怎么实现呢？

**Comment by xuanye** [comment]
> 请问glue模式要怎么实现呢？

没有实现

**Comment by q383186554** [comment]
请问有没有交流群 或者qq是多少

**Comment by q383186554** [comment]
> > 请问glue模式要怎么实现呢？
> 
> 没有实现

大佬qq多少啊

**Comment by xuanye** [comment]
不上QQ，不好意思

**Comment by q383186554** [comment]
> 不上QQ，不好意思

wx也行啊 有偿

**Comment by q383186554** [comment]
> > 不上QQ，不好意思
> 
> wx也行啊 有偿

欧尼酱

**Comment by xuanye** [comment]
> > > 不上QQ，不好意思
> > 
> > 
> > wx也行啊 有偿
> 
> 欧尼酱
glue 模式的本质是本地执行脚本语言，你要看你的脚本是什么lua？ python? js?还是就是C# ，你要去找对应的C#中运行对应脚本的解决方案
