### ISSUE TITLE
在.net6下使用时会报错trigger callback error:Could not load type 'Flurl.StringExtensions' from assembly 'Flurl, Version=3.0.6.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by tangjiazhu** [xuanye/DotXxlJob#39]
之前在.net5上使用一直没有问题，在.net6使用时，会报错trigger callback error:Could not load type 'Flurl.StringExtensions' from assembly 'Flurl, Version=3.0.6.0, Culture=neutral, PublicKeyToken=null'.

尝试手工安装Flurl旧版及最新版，均不能解决。
运行环境是centos docker里面运行
![image](https://github.com/xuanye/DotXxlJob/assets/37805223/e2c2822a-c8b6-4032-8500-3b8956d17b66)

**Comment by SXwangwei** [comment]
有解决吗？

**Comment by tangjiazhu** [comment]
本人已经收到邮件，看后会第一时间回复你！

**Comment by tangjiazhu** [comment]
> 有解决吗？

解决了

**Comment by tangjiazhu** [comment]
将源码下载下来，将依赖从旧版换到最新就可以了。
"Flurl.Http" Version="3.2.4"

**Comment by tangjiazhu** [comment]
Flurl.Http" Version="3.2.4"

**Comment by tangjiazhu** [comment]
本人已经收到邮件，看后会第一时间回复你！
