### ISSUE TITLE
Docker 部署的xxl-job 无法连接

### ISSUE THREAD

**Issue by wanglei8888** [xuanye/DotXxlJob#40]
![image](https://github.com/xuanye/DotXxlJob/assets/58056950/fe479902-058d-4dcf-9585-a30ae0e868a2)
这是docker部署的xxl-job 报错信息

**Comment by wanglei8888** [comment]
正常 jar 包部署的，是可以连接的。

**Comment by xuanye** [comment]
你先确保容器间的网络是通的哟
