### ISSUE TITLE
可以注册成功，任务执行不成功

### ISSUE THREAD

**Issue by lbxbj2008** [xuanye/DotXxlJob#6]
可以注册成功，任务执行不成功，是什么问题
程序运行端口是60087 ,配置文件里设置的端口是 5000或60087，都执行不成功

**Comment by Inuyasha-Monster** [comment]
> 可以注册成功，任务执行不成功，是什么问题
> 程序运行端口是60087 ,配置文件里设置的端口是 5000或60087，都执行不成功

我是注册成功了 但是admin没有显示执行器 为什么呢
![image](https://user-images.githubusercontent.com/12888788/98927009-f7163980-2512-11eb-9ea1-b528fa5de993.png)

**Comment by xuanye** [comment]
你们要把两边的配置都发出来，这样没法帮你们判断出了什么问题，楼主的问题是执行器的端口配置错误

admin的地址和端口
执行器的配置信息发出来

**Comment by Inuyasha-Monster** [comment]
> docker run -e PARAMS="--spring.datasource.url=jdbc:mysql://192.168.1.55:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=111111" -p 8080:8080 -v /tmp:/data/applogs --name xxl-job-admin -d xuxueli/xxl-job-admin:2.2.0


![image](https://user-images.githubusercontent.com/12888788/99020056-b4974000-2598-11eb-85ef-44347bf7443e.png)

上面是admin启动配置 , 接下来用您提供的simple工程连接 , 调整为上图对应的服务端配置: 
![image](https://user-images.githubusercontent.com/12888788/99020254-0c35ab80-2599-11eb-940d-6a09d6a2faf0.png)
![image](https://user-images.githubusercontent.com/12888788/99020296-2c656a80-2599-11eb-8a4c-e697b9e48a69.png)

麻烦费心了 23333

**Comment by xuanye** [comment]
你执行器绑定的是localhost ，注册的是局域网IP 当然是执行不成功了
admin来调用你http://192.168.182.134:5000 的请求是访问不成功的

**Comment by Inuyasha-Monster** [comment]
> 你执行器绑定的是localhost ，注册的是局域网IP 当然是执行不成功了
> admin来调用你http://192.168.182.134:5000 的请求是访问不成功的

调整为如下所示:
```
"xxlJob": {
    "adminAddresses": "http://192.168.182.134:8080/xxl-job-admin",
    "appName": "xxl-job-executor-dotnet",
    "specialBindAddress": "192.168.1.74",
    "port": 5000,
    "autoRegistry": true,
    "accessToken": "",
    "logRetentionDays": 30
  }
```
![image](https://user-images.githubusercontent.com/12888788/99024618-ee207900-25a1-11eb-9fb8-8abd46fe9d07.png)
![image](https://user-images.githubusercontent.com/12888788/99024644-fb3d6800-25a1-11eb-9bf8-cd1f4006a8df.png)
![image](https://user-images.githubusercontent.com/12888788/99024713-16a87300-25a2-11eb-8871-2734249fbdff.png)

总结一下: 
1. 执行器需要手动在UI配置 , 注意配置地址的完整性
2. 配置任务选择httpJobHandler方式
3. 自己没有看清楚一些配置

谢谢您的回复 , 这边自己搞清楚了, 接下来进一步测试

**Comment by xuanye** [comment]
在admin后台录入一个执行器，选择自动注册，（其实是添加一类执行器）

然后再执行器配置对应的appName 就能实现执行器的自动注册 （注册具体的机器）

  "appName": "xxl-job-executor-dotnet",

**Comment by Inuyasha-Monster** [comment]
> 在admin后台录入一个执行器，选择自动注册，（其实是添加一类执行器）
> 
> 然后再执行器配置对应的appName 就能实现执行器的自动注册 （注册具体的机器）
> 
> "appName": "xxl-job-executor-dotnet",

ok ,  3Q解答

**Comment by guoshengyang** [comment]
> 在admin后台录入一个执行器，选择自动注册，（其实是添加一类执行器）
> 
> 然后再执行器配置对应的appName 就能实现执行器的自动注册 （注册具体的机器）
> 
> "appName": "xxl-job-executor-dotnet",

有一点不理解，为什么需要手工录入一个执行器，不能全部自动的注册呢？是设计的不足还是有什么原因啊？

**Comment by xuanye** [comment]
> > 在admin后台录入一个执行器，选择自动注册，（其实是添加一类执行器）
> > 然后再执行器配置对应的appName 就能实现执行器的自动注册 （注册具体的机器）
> > "appName": "xxl-job-executor-dotnet",
> 
> 有一点不理解，为什么需要手工录入一个执行器，不能全部自动的注册呢？是设计的不足还是有什么原因啊？

存在一种情况就是executor的网络环境复杂，本机地址不是admin可以访问到的地址，需要反向代理的方式访问
