### ISSUE TITLE
注册进去无法触发

### ISSUE THREAD

**Issue by 3zengzz** [xuanye/DotXxlJob#8]
![image](https://user-images.githubusercontent.com/30330939/101887943-81b48c00-3bd8-11eb-8625-6a574fbda35a.png)
在服务器上ping程序所在的机子是通的，xia下面是job配置
![image](https://user-images.githubusercontent.com/30330939/101888080-aad51c80-3bd8-11eb-899c-7eed39b40fd9.png)
程序运行图如下：
![image](https://user-images.githubusercontent.com/30330939/101888177-c3ddcd80-3bd8-11eb-8418-3e25267aa8b4.png)
job类代码如下：
![image](https://user-images.githubusercontent.com/30330939/101888242-d6f09d80-3bd8-11eb-8098-3912d8c01e38.png)

![image](https://user-images.githubusercontent.com/30330939/101889003-ddcbe000-3bd9-11eb-92d6-b016845a22e3.png)

![image](https://user-images.githubusercontent.com/30330939/101889041-ea503880-3bd9-11eb-8435-cff4820719e5.png)

麻烦帮忙看下是什么问题？

**Comment by xuanye** [comment]
你在服务器上 试试telnet 192.168.123.102 5000 试试端口是否开通了 ，有可能是防火墙把端口阻止了

**Comment by 3zengzz** [comment]
> 你在服务器上 试试telnet 192.168.123.102 5000 试试端口是否开通了 ，有可能是防火墙把端口阻止了

你好，让运维试过，服务器是通的
![image](https://user-images.githubusercontent.com/30330939/102030096-42f71f80-3dec-11eb-9e35-2d31187d1f61.png)

进一步调试后发现
![image](https://user-images.githubusercontent.com/30330939/102044083-0b4e9e80-3e11-11eb-8532-f28b0386b201.png)

看源码把logid 的int类型改成long就可以了，另外取消中间件contenttype判断才可以触发任务
![image](https://user-images.githubusercontent.com/30330939/102036433-c40ae280-3dfd-11eb-9687-0c7f98a92d15.png)

**Comment by xuanye** [comment]
可能是因为xxl-job的各个版本的小变更导致了这个问题，毕竟没有测试所有的版本，它的release说明中也未说明这个问题 ，解决了就好

**Comment by 3zengzz** [comment]
> 可能是因为xxl-job的各个版本的小变更导致了这个问题，毕竟没有测试所有的版本，它的release说明中也未说明这个问题 ，解决了就好

能不能修复一下发个新的nuget包呀

**Comment by xuanye** [comment]
> > 可能是因为xxl-job的各个版本的小变更导致了这个问题，毕竟没有测试所有的版本，它的release说明中也未说明这个问题 ，解决了就好
> 
> 能不能修复一下发个新的nuget包呀

看了下xxl-job 对应版本的源码，并不只是你说的两个问题，底层协议也有2.0.1 和2.2的不一样，不太明白为何作者在同一个大版本中 实用三种不一样的通讯协议， 建议升级到最新版 ，旧版协议不做支持了

**Comment by Mahuanpeng** [comment]
@3zengzz 你的xxl-job是2.1.1版本的吗，Nuget包用的是1.0.8是吗，为啥我报错了
![image](https://user-images.githubusercontent.com/16773968/121480589-cdb48200-c9fd-11eb-82bc-050356d5f4c6.png)
