### ISSUE TITLE
CollectBody解析出错

### ISSUE THREAD

**Issue by madengtao** [xuanye/DotXxlJob#9]
解析Body时报错，能不能帮看下什么问题
.netCore我改成了.net5.0  xxl-job是2.2版本
因为.net版本升级不支持同步读取，所以添加了支持同步读取的配置
![image](https://user-images.githubusercontent.com/18281418/104003480-6dff4400-51dd-11eb-9cf4-77c3be788adb.png)
![image](https://user-images.githubusercontent.com/18281418/104003554-81121400-51dd-11eb-99ea-4d4e8e40c461.png)

![QQ截图20210108160615](https://user-images.githubusercontent.com/18281418/103990039-8ebe9e00-51cb-11eb-92a0-3e6015496ed3.png)

**Comment by madengtao** [comment]
我把版本改回netcoreapp2.2确实没问题，不知道5.0为什么会报错

**Comment by xuanye** [comment]
你试试把断点设置在Collectbody 函数的下方或者不设置断点 就可以正常运行了，貌似是vs的bug，

**Comment by madengtao** [comment]
> 你试试把断点设置在Collectbody 函数的下方或者不设置断点 就可以正常运行了，貌似是vs的bug，

我试了试确实不打断点就可以了，神奇
